"""initial artefact store

Revision ID: eab319ecb88e
Revises: 
Create Date: 2026-07-17 23:01:55.581619
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'eab319ecb88e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artefacts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('latest_version_no', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'name', name='uq_artefact_kind_name')
    )
    with op.batch_alter_table('artefacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artefacts_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_artefacts_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_artefacts_name'), ['name'], unique=False)

    op.create_table('artefact_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('artefact_id', sa.String(length=32), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('body', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artefact_id'], ['artefacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artefact_id', 'version_no', name='uq_version_no')
    )
    with op.batch_alter_table('artefact_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artefact_versions_artefact_id'), ['artefact_id'], unique=False)

    op.create_table('flows',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('config_artefact_id', sa.String(length=32), nullable=False),
    sa.Column('config_version_no', sa.Integer(), nullable=True),
    sa.Column('tco_artefact_id', sa.String(length=32), nullable=True),
    sa.Column('tco_version_no', sa.Integer(), nullable=True),
    sa.Column('computed_artefact_id', sa.String(length=32), nullable=True),
    sa.Column('computed_version_no', sa.Integer(), nullable=True),
    sa.Column('default_export_filename', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['computed_artefact_id'], ['artefacts.id'], ),
    sa.ForeignKeyConstraint(['config_artefact_id'], ['artefacts.id'], ),
    sa.ForeignKeyConstraint(['tco_artefact_id'], ['artefacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flows_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_flows_config_artefact_id'), ['config_artefact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flows_name'), ['name'], unique=True)

    op.create_table('runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('flow_id', sa.String(length=32), nullable=True),
    sa.Column('flow_name', sa.String(length=200), nullable=False),
    sa.Column('source_name', sa.String(length=300), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('config_version_id', sa.String(length=32), nullable=True),
    sa.Column('tco_version_id', sa.String(length=32), nullable=True),
    sa.Column('computed_version_id', sa.String(length=32), nullable=True),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_error', sa.Integer(), nullable=False),
    sa.Column('rows_cleaned', sa.Integer(), nullable=False),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('report', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('export_b64', sa.Text(), nullable=True),
    sa.Column('export_name', sa.String(length=200), nullable=True),
    sa.Column('export_format', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_flow_id'), ['flow_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_ok'), ['ok'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_ok'))
        batch_op.drop_index(batch_op.f('ix_runs_flow_id'))
        batch_op.drop_index(batch_op.f('ix_runs_created_at'))

    op.drop_table('runs')
    with op.batch_alter_table('flows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flows_name'))
        batch_op.drop_index(batch_op.f('ix_flows_config_artefact_id'))
        batch_op.drop_index(batch_op.f('ix_flows_archived'))

    op.drop_table('flows')
    with op.batch_alter_table('artefact_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artefact_versions_artefact_id'))

    op.drop_table('artefact_versions')
    with op.batch_alter_table('artefacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artefacts_name'))
        batch_op.drop_index(batch_op.f('ix_artefacts_kind'))
        batch_op.drop_index(batch_op.f('ix_artefacts_archived'))

    op.drop_table('artefacts')
    # ### end Alembic commands ###
